(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2016-12-06 09:54:11
  From session:  Amazon Echo
  Captured on:  2016-12-06 09:50:38
  From server:  EggPlant Test Environment
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

DoubleClick "Chrome"
TypeText "www.amazon.co.uk/",Return
Click "Search Bar"
TypeText "amazon echo"
Click "amazonechoinAllDepartments"
Click "Search Icon"
Click "Amazon Echo"
